apps: 
  name: RV32
  cfg: 
    log: /home/sample/logs
    regex: "^instretire:\s+(\d+)\s+([a-fA-F0-9]+)\s+([a-fA-F0-9]+)"
    plugins: 
      - instr_group
      - branch_ops
      - cache
  name: RV64
  cfg1: 
    log1: /home/sample1/logs1
    regex: "^core\s+\d+:\s+(\d*)\s+(0x[0-9a-fA-F]+)\s+\((0x[0-9a-fA-F]+)\)\s*(x[0-9]*)?(c[0-9]+[_a-z]*)?(mem)?\s*(0x[0-9a-fA-F]*)?\s*(x[0-9]*)?(c[0-9]+[_a-z]*)?(mem)?\s*(0x[0-9a-fA-F]*)?\s*(x[0-9]*)?(c[0-9]+[_a-z]*)?(mem)?\s*(0x[0-9a-fA-F]*)?"
    plugins: 
      - instr_group
      - branch_ops
      - cache
  