#L1 and L2 cache

cycles:
  # start_cycles: 100
  instructions_cycles:
    instructions_cycles:
    {add: 
      {latency : 1,
      throughput : 1},
    sub:
      {latency : 1,
      throughput : 1},
    mul:  
      {latency : 4,
      throughput : 4},
    div:
      {latency : 16,
      throughput : 16},
    rem:
      {latency : 16,
      throughput : 16},
    csr:
      {latency : 1,
      throughput : 1},
    s(a-z)l*:
      {latency : 1,
      throughput : 1},
    s(a-z)r*:
      {latency : 1,
      throughput : 1},
    j:
      {latency : 1,
      throughput : 1},
    c.:
      {latency : 1,
      throughput : 1}
      }
  flush_cycles:
    csr: 2 # pipeline_depth - 1 and 1 for csr # check once
    branch: 0
    fence.i: 2
  reset_cycles: 100 # internal reset cycles
  pipeline_depth: 2
  bus_latency: # this is inaccurate
    data: 8
    instruction: 9
  bypass_latency: 1
  structural_hazards:
    data_cache: 1
    bus: 8 # bus capacity in terms of words
  # replacemnt_latency: 257
